package com.kapas.util;

public enum SearchOperationEnum {
    EQUALITY, NEGATION, GREATER_THAN, GREATER_THAN_OR_EQUALS, LESS_THAN, LESS_THAN_OR_EQUALS, LIKE, STARTS_WITH, ENDS_WITH, CONTAINS, BETWEEN, NULL, NOTNULL, IN;
}
